Dispatch an event if there is an exception
AOEpeople/Aoe_DbRetry pull request #5
Opened 2015-12-15 16:37 UTC by mpchadwick

Allows others to hook in if there are other requirements (e.g. alerting system).

Based on discussions in #4

2015-12-30 14:48 UTC, mpchadwick commented
@LeeSaferite Any thoughts on this?

2016-08-19 11:45 UTC, sprankhub commented
:+1:

2017-06-22 12:52 UTC, kesonno commented
+1 for this addition 👍

2017-06-22 13:20 UTC, LeeSaferite commented
I see no reason not to merge this, but I no longer work for AOE and not longer have merge permissions.

@fbrnc

2017-06-23 17:58 UTC, LeeSaferite requested changes

2017-06-23 17:58 UTC, LeeSaferite commented on app/code/community/Aoe/DbRetry/Resource/Db/Pdo/Mysql/Adapter.php
> +                    Mage::dispatchEvent('aoe_dbretry_exception', ['try' => $try, 'exception' => $e]);
I think my only input here would be to document the event in the readme and be VERY clear that further DB calls in the event handler are unsupported and dangerous.

2018-01-25 10:05 UTC, merged